spring.application.name=CaboreApplication

# Conexión a MariaDB (XAMPP)
spring.datasource.url=jdbc:mariadb://localhost:3307/cabore
spring.datasource.password=TU_CONTRASEÑA_AQUI
spring.datasource.username=root
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# Thymeleaf
spring.thymeleaf.cache=false